### ISSUE TITLE
Problem with specific DOS3.3 image (specifies sector size = 1 byte)

### ISSUE THREAD

**Issue by jepler** [paleotronic/diskm8#20]
I notice that even aside from #19 diskm8 is not happy with [a particular disk image from archive.org](https://archive.org/download/Arcade_Games_Collection_Side_1) -- it appears to be because the VTOC claims the sector size is 1 byte, rather than 256 bytes. An Apple //e emulator (mame) is able to read the CATALOG of this disk just fine.

I didn't find any evidence of DOS 3.3 devices that ever used a sector size besides 256 bytes.

The idea that it's the sector size specification is due to finding that ignoring the sector size was the key to making the same image "work" in atrcopy:
 * https://github.com/robmcmullen/atrcopy/issues/14

**Comment by undefinedopcode** [comment]
Added a fix in 0.6.0. Thanks for finding this.

**Comment by jepler** [comment]
Cool, thank you!
