### ISSUE TITLE
tokenizing "HGR2" string results in "HGR 2" string in file on disk

### ISSUE THREAD

**Issue by fanfani** [paleotronic/diskm8#4]
hello there,

let's say i write the following simple "TEST.BAS" program using my favourite text editor (nano) on my linux system:

```
10 REM HELLO
20 HGR2
30 REM HELLO AGAIN
```

i can put it in a disk image with diskm8 as follows:

```
(c) 2015 - 2018 Paleotronic.com

dsk:0:<no mount>:[       ]> mount test.do

mount disk in slot 0

dsk:0:test.do:> put TEST.BAS

Backed up disk to: test.do.20180407163655
Updated disk test.do

dsk:0:test.do:> unmount

Unmounted volume
```

then i load up the disk image in microm8 (or any other emulator) and i get the following:

```
] LOAD TEST
] LIST

 10 REM HELLO
 20  HGR 2
 30 REM HELLO AGAIN
```

it looks that some stuff gets inserted in the "HGR2" string. what is going on?

running the program results in a SYNTAX ERROR as the string "20  HGR 2" is not considered valid, so probably some weird character (that looks like space but is not) gets inserted in the string.

**Comment by mancausoft** [comment]
Watching the code:
https://github.com/paleotronic/diskm8/blob/75d42c4597abe3b847a49b5986f682f327803bb0/disk/atokens.go#L569-L591

from the code it's easy to see that HGR is detected insted of HGR2 and tokenize as HGR.

**Comment by undefinedopcode** [comment]
This has been fixed in the current release.
